name: sanity
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-java@v6
      with:
        java-version: '26'
        distribution: 'temurin'
        cache: maven
    - run: |
        cat <<'EOF' > /home/runner/work/orchestrator.properties
        # version of SonarQube Server
        sonar.runtimeVersion=LATEST_RELEASE
  
        orchestrator.updateCenterUrl=http://update.sonarsource.org/update-center-dev.properties

        # The location of the Maven local repository is not automatically guessed. It can also be set with the env variable MAVEN_LOCAL_REPOSITORY.
        maven.localRepository=/home/runner/.m2/repository
        EOF
    - run: |
        cd java-checks-test-sources
        mvn install | tee -a out
        cd ../java-checks
        mvn install | tee -a out
      env:
        ORCHESTRATOR_CONFIG_URL: file:///home/runner/work/orchestrator.properties
        MAVEN_OPTS: "-Xmx8g"
    - run: tail -1000 out
